name: Deploy AI Agent to AWS

on:
  push:
    branches:
      - main # This tells GitHub to only run when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: SSH into AWS and Deploy
      uses: appleboy/ssh-action@master
      env:
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
      with:
        host: ${{ secrets.EC2_HOST_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd finance-project
          git pull origin main
          sudo docker build -t ai-agent .
          # Stop the old container before starting the new one
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker run -d -p 8501:8501 ai-agent